### ISSUE TITLE
Переводы

### ISSUE THREAD

**Issue by temporaldarkness** [ss14-ganimed/ENT14-Master#16]
### Описание

С насильным накидыванием русской локализации без смазки наверняка где-то да сохранились ее косяки. Объявляю **бесконечную** имбу крестового похода против косноязычия! Внесите свой вклад в правку перевода, основываясь на собственных предупреждениях или на наших братьев с Корвакса.
Аве, братья!

**Comment by Yuoko** [comment]
спай помнится разрешил EVA переводить не как ЕВА а как ВКД (ВнеКорабельная Деятельность), по хорошему перевести ибо EVA и переводится как ВКД. Ещё я бы переименовал скафандры в риги, на манер 13, но это дело привычки и просто звучит круче, делайте как хотите. Но EVA сделать ВКД!

**Comment by Yuoko** [comment]
![image](https://github.com/ss14-ganimed/ENT14-Master/assets/128321596/79605fa9-5b3f-4aaa-bda1-8a125b59e8e2)
