### ISSUE TITLE
Прототип спавна отряда смерти

### ISSUE THREAD

**Issue by temporaldarkness** [ss14-ganimed/ENT14-Master#59]
### Описание

Добавление рабочего прототипа спавна пресетов сущностей гуманоидов отряда смерти на основе уже имеющегося пресета ОБР в меню спавна сущностей. Пресет должен содержать полный вариант экипировки члена отряда.

Готовый файл пресета .yml должен содержать только английский вариант текста. Для перевода на русский следует создать .ftl файл перевода в соответствующем каталоге.

**Comment by Morgan3061** [comment]
[69b2e7058136a0f2.zip](https://github.com/ss14-ganimed/ENT14-Master/files/13061477/69b2e7058136a0f2.zip)

**Comment by Morgan3061** [comment]
Проверь на работоспособность
